# Generated by Django 4.0.5 on 2022-06-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
