# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/authorization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/authorization.proto\x12\rauthorization\"\x16\n\x14\x41uthorizationRequest\"%\n\x15\x41uthorizationResponse\x12\x0c\n\x04resp\x18\x01 \x01(\x03\x32\xd1\x03\n\rAuthorization\x12T\n\x07isAdmin\x12#.authorization.AuthorizationRequest\x1a$.authorization.AuthorizationResponse\x12Z\n\risBankManager\x12#.authorization.AuthorizationRequest\x1a$.authorization.AuthorizationResponse\x12\\\n\x0fisBranchManager\x12#.authorization.AuthorizationRequest\x1a$.authorization.AuthorizationResponse\x12W\n\nisEmployee\x12#.authorization.AuthorizationRequest\x1a$.authorization.AuthorizationResponse\x12W\n\nisCustomer\x12#.authorization.AuthorizationRequest\x1a$.authorization.AuthorizationResponseb\x06proto3')



_AUTHORIZATIONREQUEST = DESCRIPTOR.message_types_by_name['AuthorizationRequest']
_AUTHORIZATIONRESPONSE = DESCRIPTOR.message_types_by_name['AuthorizationResponse']
AuthorizationRequest = _reflection.GeneratedProtocolMessageType('AuthorizationRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZATIONREQUEST,
  '__module__' : 'protos.authorization_pb2'
  # @@protoc_insertion_point(class_scope:authorization.AuthorizationRequest)
  })
_sym_db.RegisterMessage(AuthorizationRequest)

AuthorizationResponse = _reflection.GeneratedProtocolMessageType('AuthorizationResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZATIONRESPONSE,
  '__module__' : 'protos.authorization_pb2'
  # @@protoc_insertion_point(class_scope:authorization.AuthorizationResponse)
  })
_sym_db.RegisterMessage(AuthorizationResponse)

_AUTHORIZATION = DESCRIPTOR.services_by_name['Authorization']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHORIZATIONREQUEST._serialized_start=45
  _AUTHORIZATIONREQUEST._serialized_end=67
  _AUTHORIZATIONRESPONSE._serialized_start=69
  _AUTHORIZATIONRESPONSE._serialized_end=106
  _AUTHORIZATION._serialized_start=109
  _AUTHORIZATION._serialized_end=574
# @@protoc_insertion_point(module_scope)
