# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/card_to_card.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/card_to_card.proto\x12\ncardToCard\"<\n\x11\x43\x61rdToCardRequest\x12\x17\n\x0f\x64\x65st_account_no\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\"2\n\x12\x43\x61rdToCardResponse\x12\x0c\n\x04resp\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\x32Y\n\ncardToCard\x12K\n\nCardToCard\x12\x1d.cardToCard.CardToCardRequest\x1a\x1e.cardToCard.CardToCardResponseb\x06proto3')



_CARDTOCARDREQUEST = DESCRIPTOR.message_types_by_name['CardToCardRequest']
_CARDTOCARDRESPONSE = DESCRIPTOR.message_types_by_name['CardToCardResponse']
CardToCardRequest = _reflection.GeneratedProtocolMessageType('CardToCardRequest', (_message.Message,), {
  'DESCRIPTOR' : _CARDTOCARDREQUEST,
  '__module__' : 'protos.card_to_card_pb2'
  # @@protoc_insertion_point(class_scope:cardToCard.CardToCardRequest)
  })
_sym_db.RegisterMessage(CardToCardRequest)

CardToCardResponse = _reflection.GeneratedProtocolMessageType('CardToCardResponse', (_message.Message,), {
  'DESCRIPTOR' : _CARDTOCARDRESPONSE,
  '__module__' : 'protos.card_to_card_pb2'
  # @@protoc_insertion_point(class_scope:cardToCard.CardToCardResponse)
  })
_sym_db.RegisterMessage(CardToCardResponse)

_CARDTOCARD = DESCRIPTOR.services_by_name['cardToCard']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CARDTOCARDREQUEST._serialized_start=41
  _CARDTOCARDREQUEST._serialized_end=101
  _CARDTOCARDRESPONSE._serialized_start=103
  _CARDTOCARDRESPONSE._serialized_end=153
  _CARDTOCARD._serialized_start=155
  _CARDTOCARD._serialized_end=244
# @@protoc_insertion_point(module_scope)
